version: "1.0"
info:
  model: int-scaffold
packages:
- name: GitRepoProjectTestProject
  gitServerName: SanthoshKUserSanthosh
  gitUrl: https://github.com/santhu736852
  gitUsername: santhu736852
  gitBranch: main
services:
- serviceName: project.gitrepoprojecttest.integrations:Test1
  packages:
  - name: GitRepoProjectTestProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.1132
